// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cosyqmkvzvdlkzaxmdkd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNvc3lxbWt2enZkbGt6YXhtZGtkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDExNTg0MzcsImV4cCI6MjA1NjczNDQzN30.pB8Js9Yx7ZHhjKnPhN5cd2o8ly5hlN7-DGnUXLclKpQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);